### ISSUE TITLE
Link in "about" description gives a 404

### ISSUE THREAD

**Issue by pnadolny13** [edgarrmondragon/meltano-dataops#122]
This link is giving me a 404 https://meltano-dataops.vercel.app/

![Screen Shot 2023-02-22 at 12 14 25 PM](https://user-images.githubusercontent.com/27376735/220704853-8087dc43-c870-46ed-ac2d-5c20fef10439.png)

**Comment by edgarrmondragon** [comment]
Oops! Thanks for lmk @pnadolny13. This should be fixed now. I changed from Vercel-managed build to GitHub actions so the deployment probably broke.
